#!/usr/bin/env bash

pushd factor > /dev/null

RESULT=$(./factor -run=euler$1)
RETURN_CODE=$?

if [ "$RESULT" -ne "$2" ]; then
	echo "prob $1 ERROR: result was $RESULT, but expected: $2"
fi

echo $RESULT

popd > /dev/null

exit $RETURN_CODE
