name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtkglext1
      - name: Download Tarball
        run: wget http://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz
      - name: Unpack Tarball
        run: tar -xf factor-linux-x86-64-0.98.tar.gz
      - name: Copy Code into factor Folder
        run: cp -R src/. factor/work
      - name: Copy prob Script up from .github/workflows/
        run: cp ./.github/workflows/prob .
      - run: ./prob  1  233168
      - run: ./prob  2  4613732
      - run: ./prob  3  6857
      - run: ./prob  4  906609
      - run: ./prob  5  232792560
      - run: ./prob  6  25164150
      - run: ./prob  7  104743
      - run: ./prob  8  23514624000
      - run: ./prob  9  31875000
      - run: ./prob 10  142913828922
      - run: ./prob 11  70600674
      - run: ./prob 12  76576500
      - run: ./prob 13  5537376230
      - run: ./prob 14  837799
      - run: ./prob 15  137846528820
      - run: ./prob 16  1366
      - run: ./prob 17  21124
      - run: ./prob 18  1074
      - run: ./prob 19  171
      - run: ./prob 20  648
      - run: ./prob 21  31626
      - run: ./prob 22  871198282
      - run: ./prob 23  4179871
      - run: ./prob 24  2783915460
      - run: ./prob 25  4782
      - run: ./prob 26  983
      - run: ./prob 27 -59231
      - run: ./prob 28  669171001
      - run: ./prob 29  9183
      - run: ./prob 30  443839
      - run: ./prob 31  73682
      - run: ./prob 32  45228
      - run: ./prob 33  100
      - run: ./prob 34  40730
      - run: ./prob 35  55
      - run: ./prob 36  872187
      - run: ./prob 37  748317
      - run: ./prob 38  932718654
      - run: ./prob 39  840
      - run: ./prob 40  210
      - run: ./prob 41  7652413
      - run: ./prob 42  162
      - run: ./prob 43  16695334890
      - run: ./prob 44  5482660
      - run: ./prob 45  1533776805
      - run: ./prob 46  5777
      - run: ./prob 47  134043
      - run: ./prob 48  9110846700
      - run: ./prob 49  296962999629
      - run: ./prob 50  997651
      - run: ./prob 52  142857
      - run: ./prob 51  121313
      - run: ./prob 52  142857
      - run: ./prob 53  4075
      - run: ./prob 54  376
      - run: ./prob 56  972
      - run: ./prob 57  153
      - run: ./prob 67  7273
      - run: ./prob 69  510510
      - run: ./prob 70  8319823
      - run: ./prob 72  303963552391
      - run: ./prob 79  73162890
      - run: ./prob 85  2772
      - run: ./prob 92  8581146
      - run: ./prob 94  518408346
      - run: ./prob 97  8739992577
      - run: ./prob 100 756872327473
      - run: ./prob 102 228
      - run: ./prob 104  ???
        if: ${{ false }}
