name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtkglext1
      - name: Download Tarball
        run: wget http://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz
      - name: Unpack Tarball
        run: tar -xf factor-linux-x86-64-0.98.tar.gz
      - name: Copy Code into factor Folder
        run: cp -R src/. factor/work
      - name: Copy prob Script up from .github/workflows/
        run: cp ./.github/workflows/prob .
      - run: ./prob  1  233168
      - name: Run Problems
        run: |
          ./prob  2  4613732
          ./prob  3  6857
          ./prob  4  906609
          ./prob  5  232792560
          ./prob  6  25164150
          ./prob  7  104743
          ./prob  8  23514624000
          ./prob  9  31875000
          ./prob 10  142913828922
          ./prob 11  70600674
          ./prob 12  76576500
          ./prob 13  5537376230
          ./prob 14  837799
          ./prob 15  137846528820
          ./prob 16  1366
          ./prob 17  21124
          ./prob 18  1074
          ./prob 19  171
          ./prob 20  648
          ./prob 21  31626
          ./prob 22  871198282
          ./prob 23  4179871
          ./prob 24  2783915460
          ./prob 25  4782
          ./prob 26  983
          ./prob 27 -59231
          ./prob 28  669171001
          ./prob 29  9183
          ./prob 30  443839
          ./prob 31  73682
          ./prob 32  45228
          ./prob 33  100
          ./prob 34  40730
          ./prob 35  55
          ./prob 36  872187
          ./prob 37  748317
          ./prob 38  932718654
          ./prob 39  840
          ./prob 40  210
          ./prob 41  7652413
          ./prob 42  162
          ./prob 43  16695334890
          ./prob 45  1533776805
          # ./prob 44  ???
          ./prob 46  5777
          ./prob 47  134043
          ./prob 48  9110846700
          ./prob 49  296962999629
          ./prob 50  997651
          ./prob 52  142857
          ./prob 51  121313
          ./prob 52  142857
          ./prob 53  4075
          ./prob 56  972
          ./prob 57  153
          ./prob 67  7273
          ./prob 69  510510
          ./prob 70  8319823
          ./prob 72  303963552391
          ./prob 79  73162890
          ./prob 85  2772
          ./prob 92  8581146
          # ./prob 94  518408346
          ./prob 97  8739992577
          ./prob 100 756872327473
          ./prob 102 228
