#!/usr/bin/env bash

pushd factor > /dev/null

RESULT=$(./factor -run=euler$1)
RETURN_CODE=$?

if [ "$RETURN_CODE" -ne "0" ]; then
	echo "FAIL: return code was $RETURN_CODE"
	echo "$RESULT"
elif [ "$RESULT" -ne "$2" ]; then
	echo "ERROR: result was $RESULT, but expected: $2"
	RETURN_CODE=1
else
	echo "SUCCESS: result was $RESULT"
fi

popd > /dev/null

exit $RETURN_CODE
